// red-social-angular/src/app/features/auth/pages/register/register.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { environment } from '../../../../../environments/environment';
import { AuthService } from '../../services/auth.service';

@Component({
	selector: 'app-register',
	standalone: true,
	imports: [CommonModule, ReactiveFormsModule, RouterModule],
	templateUrl: './register.component.html',
	styleUrl: './register.component.css'
})
export class RegisterComponent {
	registerForm: FormGroup;
	loading = false;
	errorMessage = '';

	constructor(
		private fb: FormBuilder,
		private authService: AuthService,
		private router: Router
	) {
		this.registerForm = this.fb.group({
			username: ['', [Validators.required, Validators.minLength(3)]],
			email: ['', [Validators.required, Validators.email]],
			password: ['', [Validators.required, Validators.minLength(environment.minPasswordLength)]],
			firstName: [''],
			lastName: ['']
		});
	}

	onSubmit(): void {
		if (this.registerForm.valid) {
			this.loading = true;
			this.errorMessage = '';

			this.authService.register(this.registerForm.value).subscribe({
				next: () => {
					this.router.navigate(['/']);
				},
				error: (error) => {
					this.loading = false;
					this.errorMessage = error.error?.message || 'Error al crear la cuenta';
				}
			});
		}
	}
}

<!-- register -->
<div class="min-h-screen bg-black flex items-center justify-center p-4">
  <div class="max-w-md w-full bg-white rounded-xl shadow-lg p-8">
    <h2 class="text-2xl font-bold text-gray-900 mb-6 text-center">DEV</h2>
    <div class="login-header text-center mb-4">
      <p class="text-center">Red social dev</p>
    </div>

    <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="space-y-4">
      <div>
        <label
          for="username"
          class="block text-sm font-medium text-gray-700 mb-1"
          >Nombre de usuario</label
        >
        <input
          type="text"
          id="username"
          formControlName="username"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gray-500 focus:border-gray-500 outline-none transition-all"
          placeholder="nombre de usuario"
        />
        <div
          *ngIf="
            registerForm.get('username')?.invalid &&
            registerForm.get('username')?.touched
          "
          class="error-message text-red-500 text-sm mt-1"
        >
          Nombre de usuario es requerido
        </div>
      </div>
      <div>
        <label for="email" class="block text-sm font-medium text-gray-700 mb-1"
          >Email</label
        >
        <input
          type="email"
          id="email"
          formControlName="email"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gray-500 focus:border-gray-500 outline-none transition-all"
          placeholder="your@email.com"
        />
        <div
          *ngIf="
            registerForm.get('email')?.invalid &&
            registerForm.get('email')?.touched
          "
          class="error-message text-red-500 text-sm mt-1"
        >
          Email es requerido y debe ser válido
        </div>
      </div>

      <div>
        <label
          for="password"
          class="block text-sm font-medium text-gray-700 mb-1"
          >Password</label
        >
        <input
          type="password"
          id="password"
          formControlName="password"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gray-500 focus:border-gray-500 outline-none transition-all"
          placeholder="••••••••"
        />
        <div
          *ngIf="
            registerForm.get('password')?.invalid &&
            registerForm.get('password')?.touched
          "
          class="error-message text-red-500 text-sm mt-1"
        >
          Contraseña debe tener al menos 6 caracteres
        </div>
      </div>
      <button
        type="submit"
       class="w-full bg-black hover:bg-gray-800 text-white font-medium py-2.5 rounded-lg transition-colors"
        [disabled]="registerForm.invalid || loading"
      >
        <span *ngIf="!loading">Crear Cuenta</span>
        <span *ngIf="loading">Creando cuenta...</span>
      </button>
      <div class="flex items-center justify-between">
        <label class="flex items-center">
          <div class="mt-6 text-center text-sm text-gray-600">
            ¿si tienes una cuenta?
            <a
              routerLink="/login"
              class="text-black hover:text-gray-900 font-medium"
              >Inicia sesión
            </a>
          </div>
        </label>
      </div>
    </form>
  </div>
</div>

// red-social-vue/src/views/Register.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-100">
    <section class="rounded-md p-4 bg-white shadow-md w-full max-w-md">
      <h2 class="text-2xl font-bold text-center mb-2">Registrarte</h2>
      <p class="text-gray-600 text-center mb-4">
        ¿Ya tienes una cuenta?
        <router-link to="/login" class="text-black font-semibold">Inicia Sesión</router-link>
      </p>

      <form @submit.prevent="onSubmit" class="space-y-4"> 
        <div>
          <label class="text-sm font-medium text-gray-700">Usuario *</label>
          <input
            v-model="dataForm.username"
            required
            placeholder="Usuario"
            type="text"
            class="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-black"
          />
        </div>

        <div>
          <label class="text-sm font-medium text-gray-700">Correo Electrónico *</label>
          <input
            v-model="dataForm.email"
            required
            type="email"
            placeholder="Correo"
            class="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-black"
          />
        </div>

        <div>
          <label class="text-sm font-medium text-gray-700">Contraseña *</label>
          <input
            v-model="dataForm.password"
            required
            type="password"
            placeholder="Contraseña"
            class="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-black"
          />
        </div>

        <button
          type="submit"
          :disabled="loading"
          class="w-full bg-black text-white py-2.5 rounded-md font-semibold hover:bg-black/80 transition"
        >
          <span v-if="loading">Cargando...</span>
          <span v-else>Registrarse</span>
        </button>
      </form>
    </section>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { authService } from '@/services/authService'

const router = useRouter()
const loading = ref(false)

const dataForm = reactive({
  username: '',
  email: '',
  password: ''
})

const onSubmit = async () => {
  loading.value = true
  try {
    await authService.register(dataForm)
    router.push('/login')
  } catch (error) {
    console.error('Error:', error)
    alert('Error en el registro')
  } finally {
    loading.value = false
  }
}

</script>
