// red-social-vue/src/views/Login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-100">
    <section class="rounded-md p-4 bg-white shadow-md w-full max-w-md">
      <h2 class="text-2xl font-bold text-center mb-2">Bienvenido</h2>
      <p class="text-gray-600 text-center mb-4">
        ¿No tienes una cuenta?
        <router-link to="/register" class="text-black font-semibold">Regístrate</router-link>
      </p>

      <form @submit.prevent="onSubmit" class="space-y-4">
        <div>
          <label class="text-sm font-medium text-gray-700">Correo Electrónico *</label>
          <input
            v-model="dataForm.email"
            placeholder="Correo"
            type="email"
            required
            class="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-black"
          />
        </div>

        <div>
          <label class="text-sm font-medium text-gray-700">Contraseña *</label>
          <input
            v-model="dataForm.password"
            placeholder="Contraseña"
            type="password"
            required
            class="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-black"
          />
        </div>

        <button
          type="submit"
          :disabled="loading"
          class="w-full bg-black text-white py-2.5 rounded-md font-semibold hover:bg-black/80 transition"
        >
          <span v-if="loading">Cargando...</span>
          <span v-else>Iniciar Sesión</span>
        </button>
      </form>
    </section>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { authService } from '@/services/authService'

const router = useRouter()
const loading = ref(false)

const dataForm = reactive({
  email: '',
  password: ''
})

const onSubmit = async () => {
  loading.value = true
  try {
    await authService.login(dataForm)
    router.push('/home')
  } catch (error) {
    console.error('Error:', error)
    alert('Error en el login')
  } finally {
    loading.value = false
  }
}
</script>

// red-social-angular/src/app/features/auth/pages/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { environment } from '../../../../../environments/environment';
import { AuthService } from '../../services/auth.service';

@Component({
	selector: 'app-login',
	standalone: true,
	imports: [CommonModule, ReactiveFormsModule, RouterModule],
	templateUrl: './login.component.html',
	styleUrl: './login.component.css'
})
export class LoginComponent {
	loginForm: FormGroup;
	loading = false;
	errorMessage = '';

	constructor(
		private fb: FormBuilder,
		private authService: AuthService,
		private router: Router
	) {
		this.loginForm = this.fb.group({
			email: ['', [Validators.required, Validators.email]],
			password: ['', [Validators.required, Validators.minLength(environment.minPasswordLength)]]
		});
	}

 onSubmit(): void {
	if (this.loginForm.valid) {
		this.loading = true;
		this.errorMessage = '';

		this.authService.login(this.loginForm.value).subscribe({
			next: (response) => {
				this.loading = false; // Desactiva loading antes de navegar
				this.router.navigate(['/']);
			},
			error: (error) => {
				this.loading = false;
				this.errorMessage = error.error?.message || 'Error al iniciar sesión';
			}
		});
	}
}
}

<!-- login  -->
<div class="min-h-screen bg-black flex items-center justify-center p-4">
  <div class="max-w-md w-full bg-white rounded-xl shadow-lg p-8">
    <h2 class="text-2xl font-bold text-gray-900 mb-6 text-center">DEV</h2>
    <div class="login-header text-center mb-4">
      <p class="text-center">Red social dev</p>
    </div>

    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="space-y-4">
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1"
          >Email</label
        >
        <input
          type="email"
          id="email"
          formControlName="email"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gray-500 focus:border-gray-500 outline-none transition-all"
          placeholder="your@email.com"
        />
        <div
          *ngIf="
            loginForm.get('email')?.invalid && loginForm.get('email')?.touched
          "
          class="error-message text-red-500 text-sm mt-1"
        >
          Email es requerido y debe ser válido
        </div>
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1"
          >Password</label
        >
        <input
          type="password"
          id="password"
          formControlName="password"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gray-500 focus:border-gray-500 outline-none transition-all"
          placeholder="••••••••"
        />
        <div
          *ngIf="
            loginForm.get('password')?.invalid &&
            loginForm.get('password')?.touched
          "
          class="error-message text-red-500 text-sm mt-1"
        >
          Contraseña es requerida
        </div>
      </div>

      <div class="flex items-center justify-between">
        <label class="flex items-center">
          <input
            type="checkbox"
            class="rounded border-gray-300 text-gray-900 focus:ring-gray-500"
          />
          <span class="ml-2 text-sm text-gray-600">Remember me</span>
        </label>
        <a href="#" class="text-sm text-black hover:text-gray-900"
          >Forgot password?</a
        >
      </div>

      <button
        typte="submit"
        [disabled]="loginForm.invalid || loading"
        class="w-full bg-black hover:bg-gray-800 text-white font-medium py-2.5 rounded-lg transition-colors"
      >
        <span *ngIf="!loading">Iniciar Sesión</span>
        <span *ngIf="loading">Cargando...</span>
      </button>
    </form>

    <div class="mt-6 text-center text-sm text-gray-600">
      ¿No tienes una cuenta?
      <a
        routerLink="/register"
        class="text-black hover:text-gray-900 font-medium"
        >Regístrate aquí</a
      >
    </div>
  </div>
</div>
